# Configuration for HollowKnightMC Plugin v2.0.0

# Global plugin settings
Plugin:
  AutoEnableKnight: true
  AutoEnableHornet: false
  ShowScoreboard: true
  ScoreboardTitle: "§6§lHollow Knight Stats"

# Knight Player Configuration
Knight:
  Enabled: true
  
  # Health settings (in half-hearts, 20 = 10 hearts)
  MaxHealth: 18.0
  StartingHealth: 10.0
  
  # Movement settings
  WalkSpeed: 0.25
  FlySpeed: 0.1
  JumpBoost: 2
  
  # Player size scaling (1.0 = normal size)
  PlayerScale: 0.8
  
  # Dash ability
  Dash:
    Enabled: true
    Cooldown: 40
    Distance: 8.0
    Height: 0.3
    InvulnerabilityTicks: 10
    
  # Wall jump ability
  WallJump:
    Enabled: true
    Cooldown: 20
    Height: 1.2
    HorizontalBoost: 0.8
    
  # Double jump ability
  DoubleJump:
    Enabled: true
    Cooldown: 10
    Height: 1.0
    
  # Soul abilities
  Soul:
    Enabled: true
    MaxSoul: 99
    StartingSoul: 33
    SoulPerKill: 11
    SoulPerHit: 3
    
    # Focus (healing) ability
    Focus:
      Enabled: true
      SoulCost: 33
      HealAmount: 2.0
      CastTime: 60
      
    # Vengeful Spirit (projectile) ability - LEFT CLICK
    VengefulSpirit:
      Enabled: true
      SoulCost: 11
      Damage: 4.0
      Speed: 2.0
      Range: 20.0
      
  # Combat settings
  Combat:
    MeleeDamage: 3.0
    AttackSpeed: 1.5
    KnockbackResistance: 0.2
    
  # Visual effects
  Effects:
    DashParticles: true
    SoulParticles: true
    HealingParticles: true
    AttackParticles: true

# Hornet Player Configuration
Hornet:
  Enabled: true
  
  # Health settings (in half-hearts, 20 = 10 hearts)
  MaxHealth: 16.0
  StartingHealth: 12.0
  
  # Movement settings (Hornet is faster than Knight)
  WalkSpeed: 0.3
  FlySpeed: 0.15
  JumpBoost: 3
  
  # Player size scaling
  PlayerScale: 0.85
  
  # Dash ability
  Dash:
    Enabled: true
    Cooldown: 30
    Distance: 10.0
    Height: 0.4
    InvulnerabilityTicks: 8
    
  # Silk system
  Silk:
    Enabled: true
    MaxSilk: 50
    StartingSilk: 25
    SilkPerKill: 5
    SilkPerHit: 2
    
  # Needle throw ability - LEFT CLICK
  NeedleThrow:
    Enabled: true
    SilkCost: 5
    Damage: 5.0
    Speed: 2.5
    Range: 25.0
    
  # Silk trap ability - RIGHT CLICK
  SilkTrap:
    Enabled: true
    SilkCost: 15
    Duration: 300
    
  # Combat settings
  Combat:
    MeleeDamage: 4.0
    AttackSpeed: 2.0
    KnockbackResistance: 0.1
    
  # Visual effects
  Effects:
    DashParticles: true
    SilkParticles: true
    AttackParticles: true

# Boss configurations - Hollow Knight Bosses
Bosses:
  # 1. Hornet
  hornet:
    Enabled: true
    Health: 80.0
    Speed: 0.4
    Damage: 6.0
    SpawnChance: 0.1
    
  # 2. The Knight (Shadow)
  shadowknight:
    Enabled: true
    Health: 60.0
    Speed: 0.35
    Damage: 5.0
    SpawnChance: 0.08
    
  # 3. Mantis Lords
  mantislord:
    Enabled: true
    Health: 100.0
    Speed: 0.45
    Damage: 8.0
    SpawnChance: 0.05
    
  # 4. Soul Master
  soulmaster:
    Enabled: true
    Health: 120.0
    Speed: 0.3
    Damage: 7.0
    SpawnChance: 0.04
    
  # 5. Dung Defender
  dungdefender:
    Enabled: true
    Health: 140.0
    Speed: 0.25
    Damage: 6.0
    SpawnChance: 0.03
    
  # 6. Broken Vessel
  brokenvessel:
    Enabled: true
    Health: 90.0
    Speed: 0.3
    Damage: 7.0
    SpawnChance: 0.06
    
  # 7. Crystal Guardian
  crystalguardian:
    Enabled: true
    Health: 110.0
    Speed: 0.2
    Damage: 8.0
    SpawnChance: 0.04
    
  # 8. Watcher Knights
  watcherknight:
    Enabled: true
    Health: 130.0
    Speed: 0.35
    Damage: 9.0
    SpawnChance: 0.03
    
  # 9. Traitor Lord
  traitorlord:
    Enabled: true
    Health: 160.0
    Speed: 0.4
    Damage: 10.0
    SpawnChance: 0.02
    
  # 10. Grimm
  grimm:
    Enabled: true
    Health: 200.0
    Speed: 0.5
    Damage: 12.0
    SpawnChance: 0.01
    
  # 11. The Radiance
  radiance:
    Enabled: true
    Health: 300.0
    Speed: 0.6
    Damage: 15.0
    SpawnChance: 0.005
    
  # 12. Nightmare King Grimm
  nightmarekingrimm:
    Enabled: true
    Health: 250.0
    Speed: 0.7
    Damage: 18.0
    SpawnChance: 0.003
    
  # 13. Absolute Radiance
  absoluteradiance:
    Enabled: true
    Health: 400.0
    Speed: 0.8
    Damage: 20.0
    SpawnChance: 0.001
    
  # 14. Pure Vessel
  purevessel:
    Enabled: true
    Health: 180.0
    Speed: 0.6
    Damage: 14.0
    SpawnChance: 0.01
    
  # 15. Sisters of Battle
  sistersofbattle:
    Enabled: true
    Health: 150.0
    Speed: 0.5
    Damage: 12.0
    SpawnChance: 0.02

# Silksong Bosses
  # 16. Lace
  lace:
    Enabled: true
    Health: 120.0
    Speed: 0.6
    Damage: 10.0
    SpawnChance: 0.03
    
  # 17. Moss Mother
  moss:
    Enabled: true
    Health: 180.0
    Speed: 0.3
    Damage: 12.0
    SpawnChance: 0.02
    
  # 18. Sharpe
  sharpe:
    Enabled: true
    Health: 100.0
    Speed: 0.4
    Damage: 8.0
    SpawnChance: 0.04
    
  # 19. Gannet
  gannet:
    Enabled: true
    Health: 90.0
    Speed: 0.7
    Damage: 7.0
    SpawnChance: 0.05
    
  # 20. Carmelita
  carmelita:
    Enabled: true
    Health: 110.0
    Speed: 0.5
    Damage: 9.0
    SpawnChance: 0.03
    
  # 21. Macabre
  macabre:
    Enabled: true
    Health: 160.0
    Speed: 0.4
    Damage: 13.0
    SpawnChance: 0.02
    
  # 22. Krow
  krow:
    Enabled: true
    Health: 140.0
    Speed: 0.6
    Damage: 11.0
    SpawnChance: 0.025
    
  # 23. Bone Bottom
  bonebottom:
    Enabled: true
    Health: 200.0
    Speed: 0.3
    Damage: 15.0
    SpawnChance: 0.015
    
  # 24. Seth
  seth:
    Enabled: true
    Health: 220.0
    Speed: 0.5
    Damage: 16.0
    SpawnChance: 0.01
    
  # 25. Coral
  coral:
    Enabled: true
    Health: 190.0
    Speed: 0.4
    Damage: 14.0
    SpawnChance: 0.02

# Original Nosk configuration
Nosk:
  Enabled: true
  Health: 52.0
  Speed: 0.3
  ShapeShiftCooldown: 200
  DashCooldown: 60
  DashSpeed: 1.5
  DashHeight: 0.2
  BlobSpitCooldown: 40
  BlobSpeed: 1.2
  TargetRange: 16.0