# Main Configuration for HollowKnightMC Plugin v2.0.0

# Global plugin settings
Plugin:
  ShowScoreboard: true
  ScoreboardTitle: "§6§l⚔ HOLLOW KNIGHT ⚔"
  RequireClassSelection: false
  DefaultClass: "none" # none, knight, hornet
  AutoEnableAbilities: false
  
# Addon System
Addons:
  Enabled: true
  LoadFromFolder: true
  FolderName: "abilities"
  
# Visual Effects
Effects:
  ParticleMultiplier: 1.0
  SoundVolume: 1.0
  FallingBlockEffects: true
  AdvancedParticles: true
  
# Scoreboard Settings
Scoreboard:
  UpdateInterval: 5 # ticks
  ShowCurrentAction: true
  ShowCooldowns: true
  ShowStats: true
  AnimatedTitle: true