name: HollowKnightMC
version: '2.0.0'
main: com.hihelloy.hollowKnightMC.HollowKnightMC
api-version: '1.20'
author: hihelloy
description: A comprehensive Minecraft plugin that adds Hollow Knight and Silksong content
website: https://github.com/hihelloy/hollow-knight-mc

depend: [LibsDisguises]

commands:
  nosk:
    description: Spawn a Nosk entity
    usage: /nosk
    permission: hollowknightmc.nosk
  knight:
    description: Manage Knight abilities
    usage: /knight [toggle|soul|reload]
    permission: hollowknightmc.knight
  hornet:
    description: Manage Hornet abilities
    usage: /hornet [toggle|silk|reload]
    permission: hollowknightmc.hornet
  hkmc:
    description: Main HollowKnightMC commands
    usage: /hkmc [spawn|list|reload]
    permission: hollowknightmc.admin

permissions:
  hollowknightmc.*:
    description: All HollowKnightMC permissions
    default: op
    children:
      hollowknightmc.knight: true
      hollowknightmc.hornet: true
      hollowknightmc.nosk: true
      hollowknightmc.admin: true
  hollowknightmc.knight:
    description: Allows using Knight abilities
    default: true
  hollowknightmc.hornet:
    description: Allows using Hornet abilities
    default: true
  hollowknightmc.nosk:
    description: Allows spawning Nosk entities
    default: op
  hollowknightmc.admin:
    description: Allows admin commands
    default: op